const dietsData = {
  diets: [
    {
      id: 'hypocaloric',
      name: 'Hipocalórica',
      icon: 'scale',
      description: 'Ideal para pérdida de peso controlada',
      features: ['Bajo en calorías', 'Alto en fibra', 'Saciante'],
      recipeCount: 6
    },
    {
      id: 'hyperproteic',
      name: 'Hiperproteica',
      icon: 'dumbbell',
      description: 'Para aumento de masa muscular',
      features: ['Alto en proteínas', 'Construcción muscular', 'Recuperación'],
      recipeCount: 6
    },
    {
      id: 'vegetarian',
      name: 'Vegetariana',
      icon: 'leaf',
      description: 'Sin carne, incluye lácteos y huevos',
      features: ['Sin carne', 'Lácteos OK', 'Huevos OK'],
      recipeCount: 6
    },
    {
      id: 'vegan',
      name: 'Vegana',
      icon: 'sprout',
      description: 'Completamente libre de productos animales',
      features: ['100% vegetal', 'Sin lácteos', 'Sin huevos'],
      recipeCount: 6
    },
    {
      id: 'ketogenic',
      name: 'Cetogénica',
      icon: 'flame',
      description: 'Alta en grasas, muy baja en carbohidratos',
      features: ['Bajo en carbos', 'Alto en grasas', 'Cetosis'],
      recipeCount: 6
    }
  ],
  recipes: [
    {
      id: 1,
      name: 'Ensalada de Pollo y Verduras',
      dietType: 'hypocaloric',
      dietTypeName: 'Hipocalórica',
      description: 'Ensalada fresca con pechuga de pollo a la plancha',
      time: '20 min',
      difficulty: 'Fácil',
      rating: 4.7,
      calories: 280,
      image: 'https://images.unsplash.com/photo-1546793665-c74683f339c1?w=400&h=300&fit=crop'
    },
    {
      id: 2,
      name: 'Sopa de Verduras',
      dietType: 'hypocaloric',
      dietTypeName: 'Hipocalórica',
      description: 'Sopa casera baja en calorías',
      time: '30 min',
      difficulty: 'Fácil',
      rating: 4.5,
      calories: 150,
      image: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?w=400&h=300&fit=crop'
    },
    {
      id: 3,
      name: 'Pescado al Vapor con Limón',
      dietType: 'hypocaloric',
      dietTypeName: 'Hipocalórica',
      description: 'Filete de pescado blanco al vapor',
      time: '25 min',
      difficulty: 'Fácil',
      rating: 4.6,
      calories: 220,
      image: 'https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=400&h=300&fit=crop'
    },
    {
      id: 4,
      name: 'Wrap de Verduras',
      dietType: 'hypocaloric',
      dietTypeName: 'Hipocalórica',
      description: 'Wrap integral con vegetales frescos',
      time: '15 min',
      difficulty: 'Fácil',
      rating: 4.4,
      calories: 250,
      image: 'https://images.unsplash.com/photo-1626700051175-6818013e1d4f?w=400&h=300&fit=crop'
    },
    {
      id: 5,
      name: 'Yogur con Frutos Rojos',
      dietType: 'hypocaloric',
      dietTypeName: 'Hipocalórica',
      description: 'Yogur griego bajo en grasa con frutos del bosque',
      time: '5 min',
      difficulty: 'Fácil',
      rating: 4.8,
      calories: 180,
      image: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?w=400&h=300&fit=crop'
    },
    {
      id: 6,
      name: 'Wok de Vegetales',
      dietType: 'hypocaloric',
      dietTypeName: 'Hipocalórica',
      description: 'Salteado de verduras mixtas',
      time: '18 min',
      difficulty: 'Media',
      calories: 200,
      rating: 4.5,
      image: 'https://images.unsplash.com/photo-1512058564366-18510be2db19?w=400&h=300&fit=crop'
    },
    {
      id: 7,
      name: 'Pechuga de Pollo a la Plancha',
      dietType: 'hyperproteic',
      dietTypeName: 'Hiperproteica',
      description: 'Pechuga con especias y arroz integral',
      time: '25 min',
      difficulty: 'Fácil',
      rating: 4.8,
      calories: 420,
      image: 'https://images.unsplash.com/photo-1598103442097-8b74394b95c6?w=400&h=300&fit=crop'
    },
    {
      id: 8,
      name: 'Huevos Revueltos con Claras',
      dietType: 'hyperproteic',
      dietTypeName: 'Hiperproteica',
      description: 'Revuelto alto en proteínas con vegetales',
      time: '10 min',
      difficulty: 'Fácil',
      rating: 4.6,
      calories: 250,
      image: 'https://images.unsplash.com/photo-1525351484163-7529414344d8?w=400&h=300&fit=crop'
    },
    {
      id: 9,
      name: 'Salmón con Quinoa',
      dietType: 'hyperproteic',
      dietTypeName: 'Hiperproteica',
      description: 'Filete de salmón con quinoa y espárragos',
      time: '30 min',
      difficulty: 'Media',
      rating: 4.9,
      calories: 480,
      image: 'https://images.unsplash.com/photo-1485963631004-f2f00b1d6606?w=400&h=300&fit=crop'
    },
    {
      id: 10,
      name: 'Batido Proteico',
      dietType: 'hyperproteic',
      dietTypeName: 'Hiperproteica',
      description: 'Smoothie con proteína en polvo y plátano',
      time: '5 min',
      difficulty: 'Fácil',
      rating: 4.7,
      calories: 320,
      image: 'https://images.unsplash.com/photo-1505252585461-04db1eb84625?w=400&h=300&fit=crop'
    },
    {
      id: 11,
      name: 'Atún con Garbanzos',
      dietType: 'hyperproteic',
      dietTypeName: 'Hiperproteica',
      description: 'Ensalada de atún con garbanzos cocidos',
      time: '15 min',
      difficulty: 'Fácil',
      rating: 4.5,
      calories: 380,
      image: 'https://images.unsplash.com/photo-1623428187969-5da2dcea5ebf?w=400&h=300&fit=crop'
    },
    {
      id: 12,
      name: 'Filete de Ternera',
      dietType: 'hyperproteic',
      dietTypeName: 'Hiperproteica',
      description: 'Carne magra con batata asada',
      time: '35 min',
      difficulty: 'Media',
      rating: 4.8,
      calories: 520,
      image: 'https://images.unsplash.com/photo-1600891964092-4316c288032e?w=400&h=300&fit=crop'
    },
    {
      id: 13,
      name: 'Lasaña Vegetariana',
      dietType: 'vegetarian',
      dietTypeName: 'Vegetariana',
      description: 'Lasaña con verduras y queso ricotta',
      time: '50 min',
      difficulty: 'Media',
      rating: 4.8,
      calories: 380,
      image: 'https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=400&h=300&fit=crop'
    },
    {
      id: 14,
      name: 'Pizza Margarita',
      dietType: 'vegetarian',
      dietTypeName: 'Vegetariana',
      description: 'Pizza casera con tomate y mozzarella',
      time: '40 min',
      difficulty: 'Media',
      rating: 4.9,
      calories: 450,
      image: 'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=400&h=300&fit=crop'
    },
    {
      id: 15,
      name: 'Tortilla de Patatas',
      dietType: 'vegetarian',
      dietTypeName: 'Vegetariana',
      description: 'Tortilla española tradicional',
      time: '30 min',
      difficulty: 'Media',
      rating: 4.7,
      calories: 320,
      image: 'https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?w=400&h=300&fit=crop'
    },
    {
      id: 16,
      name: 'Risotto de Champiñones',
      dietType: 'vegetarian',
      dietTypeName: 'Vegetariana',
      description: 'Risotto cremoso con hongos y parmesano',
      time: '35 min',
      difficulty: 'Media',
      rating: 4.8,
      calories: 420,
      image: 'https://rainbowplantlife.com/wp-content/uploads/2023/01/Mushroom-Risotto-new-cover-photo-5x4-1-of-1.jpg'
    },
    {
      id: 17,
      name: 'Quiche de Espinacas',
      dietType: 'vegetarian',
      dietTypeName: 'Vegetariana',
      description: 'Tarta salada con espinacas y queso',
      time: '45 min',
      difficulty: 'Media',
      rating: 4.6,
      calories: 360,
      image: 'https://sallysbakingaddiction.com/wp-content/uploads/2014/02/spinach-quiche.jpg'
    },
    {
      id: 18,
      name: 'Pasta Alfredo',
      dietType: 'vegetarian',
      dietTypeName: 'Vegetariana',
      description: 'Pasta en salsa cremosa de queso',
      time: '25 min',
      difficulty: 'Fácil',
      rating: 4.7,
      calories: 480,
      image: 'https://images.unsplash.com/photo-1612874742237-6526221588e3?w=400&h=300&fit=crop'
    },
    {
      id: 19,
      name: 'Bowl de Buddha Vegano',
      dietType: 'vegan',
      dietTypeName: 'Vegana',
      description: 'Bowl nutritivo con quinoa, aguacate y vegetales',
      time: '30 min',
      difficulty: 'Fácil',
      rating: 4.9,
      calories: 420,
      image: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=400&h=300&fit=crop'
    },
    {
      id: 20,
      name: 'Curry de Garbanzos',
      dietType: 'vegan',
      dietTypeName: 'Vegana',
      description: 'Curry cremoso de garbanzos con leche de coco',
      time: '35 min',
      difficulty: 'Media',
      rating: 4.8,
      calories: 380,
      image: 'https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?w=400&h=300&fit=crop'
    },
    {
      id: 21,
      name: 'Hamburguesa de Lentejas',
      dietType: 'vegan',
      dietTypeName: 'Vegana',
      description: 'Burger vegetal con pan integral',
      time: '25 min',
      difficulty: 'Media',
      rating: 4.7,
      calories: 340,
      image: 'https://images.unsplash.com/photo-1520072959219-c595dc870360?w=400&h=300&fit=crop'
    },
    {
      id: 22,
      name: 'Smoothie Verde Detox',
      dietType: 'vegan',
      dietTypeName: 'Vegana',
      description: 'Batido de espinacas, plátano y leche de almendras',
      time: '5 min',
      difficulty: 'Fácil',
      rating: 4.6,
      calories: 220,
      image: 'https://images.unsplash.com/photo-1610970881699-44a5587cabec?w=400&h=300&fit=crop'
    },
    {
      id: 23,
      name: 'Pad Thai Vegano',
      dietType: 'vegan',
      dietTypeName: 'Vegana',
      description: 'Fideos tailandeses con tofu y vegetales',
      time: '30 min',
      difficulty: 'Media',
      rating: 4.8,
      calories: 400,
      image: 'https://images.unsplash.com/photo-1559314809-0d155014e29e?w=400&h=300&fit=crop'
    },
    {
      id: 24,
      name: 'Tacos de Tofu',
      dietType: 'vegan',
      dietTypeName: 'Vegana',
      description: 'Tacos con tofu marinado y guacamole',
      time: '20 min',
      difficulty: 'Fácil',
      rating: 4.7,
      calories: 320,
      image: 'https://images.unsplash.com/photo-1551504734-5ee1c4a1479b?w=400&h=300&fit=crop'
    },
    {
      id: 25,
      name: 'Aguacate Relleno',
      dietType: 'ketogenic',
      dietTypeName: 'Cetogénica',
      description: 'Aguacate con huevo y tocino',
      time: '15 min',
      difficulty: 'Fácil',
      rating: 4.8,
      calories: 380,
      image: 'https://rantsfrommycrazykitchen.com/wp-content/uploads/2018/05/Breakfast-Stuffed-Avocados.jpg'
    },
    {
      id: 26,
      name: 'Salmón con Mantequilla',
      dietType: 'ketogenic',
      dietTypeName: 'Cetogénica',
      description: 'Filete de salmón con mantequilla de ajo',
      time: '25 min',
      difficulty: 'Media',
      rating: 4.9,
      calories: 520,
      image: 'https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=400&h=300&fit=crop'
    },
    {
      id: 27,
      name: 'Huevos con Bacon',
      dietType: 'ketogenic',
      dietTypeName: 'Cetogénica',
      description: 'Huevos revueltos con bacon crujiente',
      time: '12 min',
      difficulty: 'Fácil',
      rating: 4.7,
      calories: 450,
      image: 'https://images.unsplash.com/photo-1525351484163-7529414344d8?w=400&h=300&fit=crop'
    },
    {
      id: 28,
      name: 'Pizza Keto',
      dietType: 'ketogenic',
      dietTypeName: 'Cetogénica',
      description: 'Pizza con base de coliflor y queso',
      time: '35 min',
      difficulty: 'Media',
      rating: 4.6,
      calories: 380,
      image: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=400&h=300&fit=crop'
    },
    {
      id: 29,
      name: 'Chuletas de Cerdo',
      dietType: 'ketogenic',
      dietTypeName: 'Cetogénica',
      description: 'Chuletas jugosas con espárragos',
      time: '30 min',
      difficulty: 'Media',
      rating: 4.8,
      calories: 540,
      image: 'https://images.unsplash.com/photo-1432139555190-58524dae6a55?w=400&h=300&fit=crop'
    },
    {
      id: 30,
      name: 'Ensalada César Keto',
      dietType: 'ketogenic',
      dietTypeName: 'Cetogénica',
      description: 'Ensalada césar sin crutones con pollo',
      time: '15 min',
      difficulty: 'Fácil',
      rating: 4.7,
      calories: 420,
      image: 'https://images.unsplash.com/photo-1546793665-c74683f339c1?w=400&h=300&fit=crop'
    }
  ]
};
